route:
  group_by: ['alertname', 'cluster']
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: 'login@gmail.com'
    from: 'login@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'login@gmail.com'
    auth_identity: 'login@gmail.com'
    auth_password: 'password'
    send_resolved: true