version: "3.8"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - $PWD/prometheus:/etc/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
     - 9093:9093
    volumes:
      - $PWD/alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager_mail.yml'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
     - "3000:3000"
    volumes:
      - $PWD/grafana:/var/lib/grafana
    depends_on:
      - prometheus

  elasticsearch:
    image: elasticsearch:7.14.2
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
        - "discovery.type=single-node"
        - "ES_JAVA_OPTS=-Xms1500m -Xmx1500m"
        - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
        - 9200:9200
        - 9300:9300
    volumes:
        - $PWD/elasticsearch:/usr/share/elasticsearch/data
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.30'
    #       memory: 1500M
        
  kibana:
    image: kibana:7.14.2
    container_name: kibana
    hostname: kibana
    ports:
        - 5601:5601
    links:
        - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 1000M
      
  logstash:
    image: logstash:7.14.2
    container_name: logstash
    hostname: logstash
    ports:
        - 9600:9600
        - 8089:8089
        - 5000:5000
    volumes:
      - $PWD/logstash:/usr/share/logstash/pipeline/
    links:
        - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 600M