groups:
- name: ApplicationAlerts
  rules:
  - alert: ApplicationDown
    expr: up == 0
    for: 15s
    labels:
      severity: critical
    annotations:
      title: 'Application {{ $labels.instance }} is down'
      description: 'Application {{ $labels.instance }} of job {{ $labels.job }} has been down for 30 seconds'
  - alert: HighTraffic
    expr: sum(rate(http_server_requests_seconds_count[15s])) > 5
    for: 30s
    labels:
      severity: warning
    annotations:
      title: 'High traffic to application {{ $labels.instance }}'