global:
  scrape_interval: 10s

rule_files:
  - 'alert.yml'
alerting:
  alertmanagers:
  - static_configs:
      - targets: ['localhost:9093']

scrape_configs:
  - job_name: 'spring_metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080']
